# Vendored from brunovicco/engineering-loop-schemas
# Version: 0.3.0
# Commit: 5340d491b46f4fabc967c81bb3e5204104b6b5d8
# Generated by scripts/render_vendor_bundle.py; do not edit by hand.
# Report-only boundary: this bundle validates schema documents only.
"""Vendored validators for Evidence-Gated Engineering Loop documents."""
