# Vendored from brunovicco/engineering-loop-schemas
# Version: 0.3.0
# Commit: 5340d491b46f4fabc967c81bb3e5204104b6b5d8
# Generated by scripts/render_vendor_bundle.py; do not edit by hand.
# Report-only boundary: this bundle validates schema documents only.
"""Small, fail-closed JSON Schema evaluator for the repository's schemas.

This is intentionally not a general-purpose JSON Schema implementation. It
implements every assertion keyword used by the four canonical schemas and
rejects a schema containing an unsupported assertion keyword. That closed
surface keeps the vendored validator standard-library-only without silently
claiming support for constraints it does not enforce.
"""

import math
import re
from datetime import datetime
from typing import Any, cast

SUPPORTED_KEYWORDS = frozenset(
    {
        "$id",
        "$schema",
        "additionalProperties",
        "allOf",
        "const",
        "contains",
        "description",
        "else",
        "enum",
        "exclusiveMinimum",
        "format",
        "if",
        "items",
        "minItems",
        "minLength",
        "minimum",
        "not",
        "pattern",
        "properties",
        "required",
        "then",
        "title",
        "type",
        "uniqueItems",
    }
)


class UnsupportedSchemaError(ValueError):
    """Raised when a canonical schema uses an assertion we do not enforce."""


def _json_equal(left: Any, right: Any) -> bool:
    """Compare decoded JSON values without Python's bool/int aliasing."""
    if isinstance(left, bool) or isinstance(right, bool):
        return type(left) is type(right) and left == right
    if isinstance(left, (int, float)) and isinstance(right, (int, float)):
        return float(left) == float(right)
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        left_mapping = cast(dict[str, Any], left)
        right_mapping = cast(dict[str, Any], right)
        return left_mapping.keys() == right_mapping.keys() and all(
            _json_equal(left_mapping[key], right_mapping[key]) for key in left_mapping
        )
    if isinstance(left, list):
        left_items = cast(list[Any], left)
        right_items = cast(list[Any], right)
        return len(left_items) == len(right_items) and all(
            _json_equal(left_item, right_item)
            for left_item, right_item in zip(left_items, right_items, strict=True)
        )
    return left == right


def _matches_type(value: Any, expected: str) -> bool:
    """Return whether a decoded value has one JSON Schema primitive type."""
    if expected == "null":
        return value is None
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return (
            isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)
        )
    if expected == "string":
        return isinstance(value, str)
    if expected == "array":
        return isinstance(value, list)
    if expected == "object":
        return isinstance(value, dict) and all(
            isinstance(key, str) for key in cast(dict[Any, Any], value)
        )
    raise UnsupportedSchemaError(f"unsupported JSON Schema type: {expected!r}")


def _is_date_time(value: str) -> bool:
    """Return whether a string is an RFC 3339-style, timezone-aware timestamp."""
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return False
    return parsed.tzinfo is not None


def assert_supported_schema(schema: dict[str, Any], path: str = "$") -> None:
    """Fail if a schema node contains an unsupported keyword."""
    unsupported = sorted(set(schema) - SUPPORTED_KEYWORDS)
    if unsupported:
        names = ", ".join(unsupported)
        raise UnsupportedSchemaError(f"{path}: unsupported schema keyword(s): {names}")

    properties = schema.get("properties")
    if isinstance(properties, dict):
        property_schemas = cast(dict[str, Any], properties)
        for name, child in property_schemas.items():
            if isinstance(child, dict):
                assert_supported_schema(
                    cast(dict[str, Any], child),
                    f"{path}.properties.{name}",
                )

    for keyword in ("items", "additionalProperties", "if", "then", "else", "not", "contains"):
        child = schema.get(keyword)
        if isinstance(child, dict):
            assert_supported_schema(cast(dict[str, Any], child), f"{path}.{keyword}")

    all_of = schema.get("allOf")
    if isinstance(all_of, list):
        for index, child in enumerate(cast(list[Any], all_of)):
            if isinstance(child, dict):
                assert_supported_schema(
                    cast(dict[str, Any], child),
                    f"{path}.allOf[{index}]",
                )


def _type_errors(value: Any, schema: dict[str, Any], path: str) -> list[str]:
    expected = schema.get("type")
    if expected is None:
        return []
    if isinstance(expected, str):
        checked_types = [expected]
    elif isinstance(expected, list) and all(
        isinstance(item, str) for item in cast(list[Any], expected)
    ):
        checked_types = cast(list[str], expected)
    else:
        raise UnsupportedSchemaError(f"{path}: schema type must be a string or string array")
    if any(_matches_type(value, item) for item in checked_types):
        return []
    return [f"{path}: expected {' or '.join(checked_types)}, got {type(value).__name__}"]


def _object_errors(value: dict[str, Any], schema: dict[str, Any], path: str) -> list[str]:
    errors: list[str] = []
    required = schema.get("required", [])
    if isinstance(required, list):
        for name in cast(list[Any], required):
            if isinstance(name, str) and name not in value:
                errors.append(f"{path}: missing required property {name!r}")

    properties = schema.get("properties", {})
    if not isinstance(properties, dict):
        raise UnsupportedSchemaError(f"{path}: properties must be an object")
    property_schemas = cast(dict[str, Any], properties)

    additional = schema.get("additionalProperties", True)
    for name, item in value.items():
        child_path = f"{path}.{name}"
        child_schema = property_schemas.get(name)
        if isinstance(child_schema, dict):
            errors.extend(validation_errors(item, cast(dict[str, Any], child_schema), child_path))
        elif additional is False:
            errors.append(f"{child_path}: additional property is not allowed")
        elif isinstance(additional, dict):
            errors.extend(validation_errors(item, cast(dict[str, Any], additional), child_path))
    return errors


def _array_errors(value: list[Any], schema: dict[str, Any], path: str) -> list[str]:
    errors: list[str] = []
    minimum = schema.get("minItems")
    if isinstance(minimum, int) and len(value) < minimum:
        errors.append(f"{path}: expected at least {minimum} item(s)")

    if schema.get("uniqueItems") is True:
        for index, item in enumerate(value):
            if any(_json_equal(item, previous) for previous in value[:index]):
                errors.append(f"{path}[{index}]: duplicate item is not allowed")

    item_schema = schema.get("items")
    if isinstance(item_schema, dict):
        for index, item in enumerate(value):
            errors.extend(
                validation_errors(
                    item,
                    cast(dict[str, Any], item_schema),
                    f"{path}[{index}]",
                )
            )

    contains = schema.get("contains")
    if isinstance(contains, dict) and not any(
        not validation_errors(
            item,
            cast(dict[str, Any], contains),
            f"{path}[{index}]",
        )
        for index, item in enumerate(value)
    ):
        errors.append(f"{path}: no item satisfies contains")
    return errors


def _scalar_errors(value: Any, schema: dict[str, Any], path: str) -> list[str]:
    errors: list[str] = []
    if isinstance(value, str):
        minimum = schema.get("minLength")
        if isinstance(minimum, int) and len(value) < minimum:
            errors.append(f"{path}: expected at least {minimum} character(s)")
        pattern = schema.get("pattern")
        if isinstance(pattern, str) and re.search(pattern, value) is None:
            errors.append(f"{path}: does not match pattern {pattern!r}")
        if schema.get("format") == "date-time" and not _is_date_time(value):
            errors.append(f"{path}: expected a timezone-aware date-time")

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        minimum_number = schema.get("minimum")
        if isinstance(minimum_number, (int, float)) and value < minimum_number:
            errors.append(f"{path}: must be greater than or equal to {minimum_number}")
        exclusive = schema.get("exclusiveMinimum")
        if isinstance(exclusive, (int, float)) and value <= exclusive:
            errors.append(f"{path}: must be greater than {exclusive}")
    return errors


def validation_errors(value: Any, schema: dict[str, Any], path: str = "$") -> list[str]:
    """Return all errors for the supported JSON Schema subset."""
    errors = _type_errors(value, schema, path)
    if errors:
        return errors

    enum = schema.get("enum")
    if isinstance(enum, list) and not any(
        _json_equal(value, item) for item in cast(list[Any], enum)
    ):
        errors.append(f"{path}: value is not in the allowed enum")
    if "const" in schema and not _json_equal(value, schema["const"]):
        errors.append(f"{path}: expected constant value {schema['const']!r}")

    if isinstance(value, dict):
        errors.extend(_object_errors(cast(dict[str, Any], value), schema, path))
    elif isinstance(value, list):
        errors.extend(_array_errors(cast(list[Any], value), schema, path))
    else:
        errors.extend(_scalar_errors(value, schema, path))

    all_of = schema.get("allOf")
    if isinstance(all_of, list):
        for child in cast(list[Any], all_of):
            if isinstance(child, dict):
                errors.extend(validation_errors(value, cast(dict[str, Any], child), path))

    condition = schema.get("if")
    if isinstance(condition, dict):
        branch = (
            "then"
            if not validation_errors(value, cast(dict[str, Any], condition), path)
            else "else"
        )
        branch_schema = schema.get(branch)
        if isinstance(branch_schema, dict):
            errors.extend(validation_errors(value, cast(dict[str, Any], branch_schema), path))

    negated = schema.get("not")
    if isinstance(negated, dict) and not validation_errors(
        value,
        cast(dict[str, Any], negated),
        path,
    ):
        errors.append(f"{path}: value matches a forbidden schema")

    return errors
