#!/usr/bin/env python3
# Vendored from brunovicco/engineering-loop-schemas
# Version: 0.3.0
# Commit: 5340d491b46f4fabc967c81bb3e5204104b6b5d8
# Generated by scripts/render_vendor_bundle.py; do not edit by hand.
# Report-only boundary: this bundle validates schema documents only.
"""Validate an Evidence-Gated Engineering Loop contract. CLI and library.

Deliberately stdlib-only so this module, its local evaluator/resource helpers,
the models, and the schemas can be vendored into a harness's quality gate
without adding a third-party dependency. YAML input is supported only if
PyYAML happens to be installed in the calling environment; JSON input always
works. See README.md for the vendoring convention.

Checks performed, after structural validation against the canonical
``contract.schema.json``:

1. scope.allowlist and scope.denylist must not overlap (as literal glob
   strings; this is a conservative, not-a-full-glob-intersection check --
   see validate_globs_disjoint()'s docstring).
2. every glob in scope.allowlist/denylist must be syntactically valid.
3. every budget value must be strictly positive.
4. every acceptance.hard_gates entry must belong to SUPPORTED_HARD_GATES.
"""

import argparse
import json
import sys
from functools import lru_cache
from pathlib import Path
from typing import Any, cast

from _vendor_loop_schemas._stdlib_jsonschema import (
    UnsupportedSchemaError,
    assert_supported_schema,
    validation_errors,
)
from _vendor_loop_schemas.models import Contract
from _vendor_loop_schemas.schema_resources import DocumentKind, load_schema

# The hard-gate names shared by both Python engineering harnesses'
# quality_gate.py scripts are already reported as named checks
# (see Check(...) entries in template/scripts/quality_gate.py in both
# harnesses). A hard gate declared in a contract must resolve to a check
# a harness's own quality gate can actually run.
SUPPORTED_HARD_GATES: frozenset[str] = frozenset(
    {
        "lock",
        "lint",
        "format",
        "typing",
        "tests",
        "security",
        "dependencies",
        "architecture",
        "mcp",
        "governance",
    }
)


class ContractValidationError(ValueError):
    """Raised by validate() callers that want a single exception on failure."""


@lru_cache(maxsize=4)
def _canonical_schema(kind: DocumentKind) -> dict[str, Any]:
    """Load and check one canonical schema once per process."""
    schema = load_schema(kind)
    assert_supported_schema(schema)
    return schema


def validate_document(data: dict[str, Any], kind: DocumentKind) -> list[str]:
    """Validate one decoded document against its canonical JSON Schema.

    The evaluator is deliberately fail-closed: if a canonical schema starts
    using a keyword the stdlib implementation does not understand, validation
    raises ``UnsupportedSchemaError`` instead of silently skipping it.
    """
    return validation_errors(data, _canonical_schema(kind))


def _is_valid_glob(pattern: str) -> bool:
    """Return whether a string is a syntactically well-formed glob.

    Uses fnmatch.translate, which never raises for arbitrary input, so this
    only rejects patterns that are empty or contain a NUL byte -- the only
    inputs that are unambiguously never a usable path glob.
    """
    return bool(pattern) and "\x00" not in pattern


def validate_globs_disjoint(allowlist: tuple[str, ...], denylist: tuple[str, ...]) -> list[str]:
    """Return errors if any glob string is literally repeated in both lists.

    This is intentionally a literal-string intersection, not a semantic
    glob-range intersection (proving two arbitrary globs never match a
    common path is not decidable in general). Authors should keep
    allowlist/denylist entries specific enough that literal overlap is the
    meaningful signal; scope enforcement at runtime always lets denylist
    win regardless of this check.
    """
    overlap = sorted(set(allowlist) & set(denylist))
    if overlap:
        return [f"scope.allowlist and scope.denylist both contain: {', '.join(overlap)}"]
    return []


def validate(data: dict[str, Any]) -> list[str]:
    """Validate a decoded contract document. Returns a list of error strings.

    An empty list means the contract is valid. Structural errors (missing
    required fields, wrong types) short-circuit and return immediately
    with a single message, since cross-field checks below assume a
    structurally valid contract to run against.
    """
    try:
        structural_errors = validate_document(data, "contract")
    except (OSError, json.JSONDecodeError, UnsupportedSchemaError) as exc:
        raise ContractValidationError(f"canonical contract schema is unavailable: {exc}") from exc
    if structural_errors:
        return [f"structural error: {error}" for error in structural_errors]

    contract = Contract.from_dict(data)

    errors: list[str] = []

    for pattern in (*contract.scope.allowlist, *contract.scope.denylist):
        if not _is_valid_glob(pattern):
            errors.append(f"scope: {pattern!r} is not a syntactically valid glob")

    errors.extend(validate_globs_disjoint(contract.scope.allowlist, contract.scope.denylist))

    action_overlap = sorted(set(contract.actions.allowed) & set(contract.actions.denied))
    if action_overlap:
        errors.append(
            "actions.allowed and actions.denied both contain: " + ", ".join(action_overlap)
        )

    budget_fields = {
        "budgets.max_tokens": contract.budgets.max_tokens,
        "budgets.max_cost_usd": contract.budgets.max_cost_usd,
        "budgets.max_wall_clock_minutes": contract.budgets.max_wall_clock_minutes,
        "budgets.max_commands": contract.budgets.max_commands,
    }
    for name, value in budget_fields.items():
        if value is not None and value <= 0:
            errors.append(f"{name} must be positive, got {value!r}")

    unsupported_gates = sorted(set(contract.acceptance.hard_gates) - SUPPORTED_HARD_GATES)
    if unsupported_gates:
        errors.append(
            "acceptance.hard_gates contains unsupported gate(s): "
            f"{', '.join(unsupported_gates)}. Supported: {', '.join(sorted(SUPPORTED_HARD_GATES))}"
        )

    if contract.trigger.type == "schedule" and not contract.trigger.schedule:
        errors.append("trigger.schedule is required when trigger.type is 'schedule'")
    if contract.trigger.type == "event" and not contract.trigger.event:
        errors.append("trigger.event is required when trigger.type is 'event'")

    return errors


def validate_evidence(data: dict[str, Any]) -> list[str]:
    """Validate a decoded evidence document against its canonical schema."""
    return validate_document(data, "evidence")


def validate_builder_result(data: dict[str, Any]) -> list[str]:
    """Validate a decoded, non-authoritative builder result."""
    return validate_document(data, "builder-result")


def validate_verdict(
    data: dict[str, Any],
    *,
    contract: dict[str, Any] | None = None,
) -> list[str]:
    """Validate a verdict and, optionally, its gate set against a contract."""
    errors = validate_document(data, "verdict")
    if errors or contract is None:
        return errors

    contract_errors = validate(contract)
    if contract_errors:
        return [f"contract: {error}" for error in contract_errors]

    if data["contract_id"] != contract["id"]:
        errors.append("verdict.contract_id does not match contract.id")

    gate_results = data["justification"]["gate_results"]
    names = [result["gate"] for result in gate_results]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        errors.append(f"verdict contains duplicate gate result(s): {', '.join(duplicates)}")

    expected = set(contract["acceptance"]["hard_gates"])
    actual = set(names)
    missing = sorted(expected - actual)
    unexpected = sorted(actual - expected)
    if missing:
        errors.append(f"verdict is missing required gate result(s): {', '.join(missing)}")
    if unexpected:
        errors.append(f"verdict contains undeclared gate result(s): {', '.join(unexpected)}")
    return errors


def load_document(path: Path) -> dict[str, Any]:
    """Load a JSON or YAML contract document from disk.

    YAML requires PyYAML to be importable; JSON never does. Raises
    ContractValidationError with an actionable message if YAML is
    requested but PyYAML is unavailable.
    """
    text = path.read_text(encoding="utf-8")
    if path.suffix in {".yaml", ".yml"}:
        try:
            import yaml  # local import: optional, YAML-only dependency
        except ImportError as exc:
            raise ContractValidationError(
                f"{path}: reading YAML contracts requires PyYAML "
                "('pip install pyyaml' or 'uv add pyyaml'); pass a .json contract instead "
                "if you cannot add that dependency here."
            ) from exc
        document = yaml.safe_load(text)
    else:
        document = json.loads(text)
    if not isinstance(document, dict):
        raise ContractValidationError(f"{path}: top-level document must be a mapping/object")
    return cast(dict[str, Any], document)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments for standalone invocation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("contract", type=Path, help="Path to a .json or .yaml/.yml contract")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Validate the contract named on the command line."""
    args = parse_args(argv)
    try:
        document = load_document(args.contract)
    except ContractValidationError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    except (OSError, json.JSONDecodeError) as exc:
        print(f"{args.contract}: could not read or parse: {exc}", file=sys.stderr)
        return 2

    try:
        errors = validate(document)
    except ContractValidationError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    if errors:
        print(f"{args.contract}: INVALID", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    print(f"{args.contract}: valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
